-- pg 库创建表 (drud 连接池报错)
CREATE TABLE dual (

);

-- SBCB.T_JXJH_DAY_PLAN_REL definition

CREATE TABLE "T_JXJH_DAY_PLAN_REL" 
   (	"PLAN_ID" VARCHAR2(100), 
	"GZP_ID" VARCHAR2(100), 
	"CZP_ID" VARCHAR2(100), 
	"PZZY_ID" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE T_JXJH_DAY_PLAN_REL IS '风控计划关联工作票、操作票,标准作业 关联表';
COMMENT ON COLUMN T_JXJH_DAY_PLAN_REL.PLAN_ID IS '计划id';
COMMENT ON COLUMN T_JXJH_DAY_PLAN_REL.GZP_ID IS '工作票id';
COMMENT ON COLUMN T_JXJH_DAY_PLAN_REL.CZP_ID IS '操作票id';
COMMENT ON COLUMN T_JXJH_DAY_PLAN_REL.PZZY_ID IS '标准作业id';


-- SBCB.T_JXJH_DAY_PLAN_REL_ACCESS definition

CREATE TABLE "T_JXJH_DAY_PLAN_REL_ACCESS" 
   (	"ACCESS_CODE" VARCHAR2(100), 
	"DISABLE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE T_JXJH_DAY_PLAN_REL_ACCESS IS '风控计划关联授权表';
COMMENT ON COLUMN T_JXJH_DAY_PLAN_REL_ACCESS.ACCESS_CODE IS '授权码';
COMMENT ON COLUMN T_JXJH_DAY_PLAN_REL_ACCESS.DISABLE IS '是否有效 0.有效 1.无效';

-- SBCB.T_JXJH_DAY_PLAN_ZDK_REL definition

CREATE TABLE "T_JXJH_DAY_PLAN_ZDK_REL" 
   (	"PLAN_ID" VARCHAR2(100), 
	"ZDK_NAME" VARCHAR2(100), 
	"FORM_VALUE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE T_JXJH_DAY_PLAN_ZDK_REL IS '风控计划  指导卡 关联';
COMMENT ON COLUMN T_JXJH_DAY_PLAN_ZDK_REL.PLAN_ID IS '计划id';
COMMENT ON COLUMN T_JXJH_DAY_PLAN_ZDK_REL.ZDK_NAME IS '指导卡名称';
COMMENT ON COLUMN T_JXJH_DAY_PLAN_ZDK_REL.FORM_VALUE IS '表单值';