@startuml "会议室流程"
(*)--> 预定会议
预定会议-->有流程
预定会议--->无流程
有流程--> 发送审批通知
if "发送审批通知" then 
--> [审批通过] 发送消息发送参会邀请
..>抄送人
..>会务人员
else 
--> [审批不通过] 发送消息给创建人
无流程--> 无流程发送通知
无流程发送通知-->参会人待办
无流程发送通知-->抄送通知
无流程发送通知-->会务人员通知
@enduml

@startwbs "导图"
+ 会议室预定

++ 会议室
+++ 会议室地址管理
++++ 关联城市
++++ 新建保存(删除,修改待规划)
+++ 会议室管理
++++ 可见范围
++++ 会议室开放时间
++++ 会议室的临时关闭
++++ 会议室删除

++ 会议预定
+++ 流程预定
++++ 需配置在后台,分公司下配置对应的流程
++++ 预定保存之后
+++++ 给对应的流程审批人员发送流程待办
+++++ 处理结果
++++++ 审批通过
+++++++ 会议室参会人员发送,会议邀请待办
+++++++ 通知会务人员,待办消息
+++++++ 通知抄送人员,待办消息
++++++ 审批不通过
+++++++ 给发起人发送不同过的待办消息

+++ 非流程预定
++++ 会议室参会人员发送,会议邀请待办
++++ 通知会务人员,待办消息
++++ 通知抄送人员,待办消息

+++ 可见范围
++++ 会议室创建人可见
++++ 参会人可见
++++ 会务人员可见
++++ 抄送人员可见

+++ 状态变化
++++ 流程 
+++++ 新建
+++++ 审批中
+++++ 审批结果
++++++ 通过 
+++++++ 待开会
+++++++ 开会中
+++++++ 结束
++++++ 不通过
+++++++ 取消
++++ 非流程
+++++ 待开会
+++++ 开会中
+++++ 结束
++++ 会议中中途取消
+++++ 取消

+++ 待办相关
++++ 待办消息,只作为查看
++++ 待办处理
+++++ 处理完成之后,直接回调对应的会议预定回写状态
+++++ 会议室开始,将未处理的待办修改成已经处理
+++++ 会议室取消,将未处理的待办修改成已经处理 ,并且发送会议取消的待办消息
+++++ 会议室中途取消,更改预定会议的状态为时间到,且会议结束,发送会议结束的待办消息

@endwbs